name: Deploy Marketing Portal

on:
  push:
    branches:
      - main
    paths:
      - 'services/portal/**'
  workflow_dispatch:


env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_DEPLOY_SERVICE_NAME: marketing-portal
  GCP_REGION: us-central1

permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/200288766686/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-deployer@bluebullfly-5cc16.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE_URL="gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_DEPLOY_SERVICE_NAME }}"
          docker build --platform linux/amd64 -t $IMAGE_URL ./services/portal
          docker push $IMAGE_URL

      - name: Deploy to Cloud Run
        run: |
          IMAGE_URL="gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_DEPLOY_SERVICE_NAME }}"
          ENV_VARS="^@^GCP_BUCKET_NAME=${{ vars.GCP_BUCKET_NAME }}"
          ENV_VARS="${ENV_VARS}@TIKTOK_CLIENT_KEY=${{ secrets.TIKTOK_CLIENT_KEY }}"
          ENV_VARS="${ENV_VARS}@TIKTOK_CLIENT_SECRET=${{ secrets.TIKTOK_CLIENT_SECRET }}"
          ENV_VARS="${ENV_VARS}@TIKTOK_REDIRECT_URI=${{ vars.TIKTOK_REDIRECT_URI }}"
          ENV_VARS="${ENV_VARS}@TIKTOK_ACCOUNT_ID=${{ vars.TIKTOK_ACCOUNT_ID }}"
          ENV_VARS="${ENV_VARS}@META_ACCESS_TOKEN=${{ secrets.META_ACCESS_TOKEN }}"
          ENV_VARS="${ENV_VARS}@META_APP_SECRET=${{ secrets.META_APP_SECRET }}"
          ENV_VARS="${ENV_VARS}@META_APP_ID=${{ vars.META_APP_ID }}"
          ENV_VARS="${ENV_VARS}@META_AD_ACCOUNT_ID=${{ vars.META_AD_ACCOUNT_ID }}"
          ENV_VARS="${ENV_VARS}@INSTAGRAM_ACCOUNT_ID=${{ vars.INSTAGRAM_ACCOUNT_ID }}"
          ENV_VARS="${ENV_VARS}@FB_PAGE_ID=${{ vars.FB_PAGE_ID }}"
          ENV_VARS="${ENV_VARS}@AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }}"
          ENV_VARS="${ENV_VARS}@AIRTABLE_BASE_ID=${{ vars.AIRTABLE_BASE_ID }}"
          ENV_VARS="${ENV_VARS}@AIRTABLE_TABLE_NAME=${{ vars.AIRTABLE_TABLE_NAME }}"
          ENV_VARS="${ENV_VARS}@GOOGLE_AISTUDIO_API_KEY=${{ secrets.GOOGLE_AISTUDIO_API_KEY }}"
          
          gcloud run deploy ${{ env.GCP_DEPLOY_SERVICE_NAME }} \
            --image $IMAGE_URL \
            --region ${{ env.GCP_REGION }} \
            --project ${{ env.GCP_PROJECT_ID }} \
            --allow-unauthenticated \
            --port 3000 \
            --set-env-vars="$ENV_VARS"
