name: Deploy Data Warehouse ETL

on:
  push:
    branches:
      - main
    paths:
      - 'services/data_warehouse/**'

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_DEPLOY_SERVICE_NAME: data-warehouse-etl
  GCP_REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/200288766686/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-deployer@bluebullfly-5cc16.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE_URL="gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_DEPLOY_SERVICE_NAME }}"
          docker build --platform linux/amd64 -t $IMAGE_URL ./services/data_warehouse
          docker push $IMAGE_URL

      - name: Deploy to Cloud Run
        run: |
          IMAGE_URL="gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_DEPLOY_SERVICE_NAME }}"
          gcloud run deploy ${{ env.GCP_DEPLOY_SERVICE_NAME }} \
            --image $IMAGE_URL \
            --region ${{ env.GCP_REGION }} \
            --project ${{ env.GCP_PROJECT_ID }} \
            --allow-unauthenticated \
            --timeout 3600
